services:
  postgres:
   image: postgres
   environment:
      POSTGRES_DB: challenge-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
   ports:
     - "5432:5432"
   expose:
     - 5432:5432
   volumes:
     
      - ./dataset:/docker-entrypoint-initdb.d
   networks: 
     - default

  redis:
   image: redis/redis-stack:latest
   ports:
     - "6379:6379"
   networks: 
     - default
 
networks:

  default:
    # Use a custom driver
    driver: bridge
   
  